import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';
import {OwnerGateway,gatewayConfig,parseOwnerCommand,redactPrivate,queryResource} from '../src/owner-gateway.mjs';
import {GroupAssistant,GROUP_TOOLS} from '../src/group-assistant.mjs';import {GroupMessageStore} from '../src/group-store.mjs';
const ctx={explicit:true,sender:'owner',chat:'A'};
function gateway(rpc,config={}){return new OwnerGateway({enabled:true,privateThreads:true,...config},{rpc,owner:()=> 'owner',allowedGroup:c=>c==='A',secrets:['REAL_SECRET_FIXTURE']});}
function fixture(t){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'gateway-'))),file=path.join(dir,'inventory.db');const db=new DatabaseSync(file);db.exec("CREATE TABLE sales(brand TEXT,amount REAL,prior REAL,hidden TEXT); INSERT INTO sales VALUES('A',30,20,'secret'),('A',50,20,'secret'),('B',10,0,'secret')");db.close();const resource={id:'inventory',type:'sqlite',displayName:'Test inventory',path:file,permissions:['read','compute'],tables:{sales:['brand','amount','prior']}};t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {resource,dir,file};}
test('disabled by default; malformed resources rejected',()=>{assert.equal(gatewayConfig().enabled,false);assert.throws(()=>gatewayConfig({resources:[{id:'x',path:'../bad'}]}));assert.throws(()=>gatewayConfig({resources:[{id:'x',type:'shell'}]}));});
for(const bad of [{sender:'member'},{sender:''},{chat:'B'},{explicit:false},{signal:AbortSignal.abort()}])test('denies before RPC '+JSON.stringify(bad),async()=>{let calls=0;const g=gateway({request:async()=>{calls++;}});await assert.rejects(g.execute('owner_thread_search',{query:'owner'}, {...ctx,...bad}));assert.equal(calls,0);});
test('search is title only; no preview cwd or secret metadata',async()=>{const methods=[];const g=gateway({request:async(m,a)=>{methods.push(m);assert.equal(a.limit,30);return {data:[{id:'one',name:'title',preview:'hidden',cwd:'/Users/private'},{id:'two',preview:'private fallback'}],nextCursor:'next'};}});const r=await g.execute('owner_thread_search',{query:'title'},ctx);assert.equal(r.threads[1].title,'未命名任务');assert.ok(!JSON.stringify(r).includes('hidden'));assert.deepEqual(methods,['thread/list']);});
test('paginated bounded read omits tool/reasoning data and redacts before model',async()=>{const methods=[];const g=gateway({request:async(m,a)=>{methods.push(m);if(m==='thread/read'){assert.equal(a.includeTurns,false);return {thread:{name:'Reference'}};}assert.equal(a.cursor,'page2');return {data:[{items:[{type:'agentMessage',text:'REAL_SECRET_FIXTURE /Users/private/config.json password=foo\n'+ 'x'.repeat(2000)},{type:'commandExecution',output:'DO NOT SEND'},{type:'reasoning',text:'DO NOT SEND'}]}],nextCursor:'page3'};}});const r=await g.execute('owner_thread_read',{threadId:'one',cursor:'page2'},ctx);assert.equal(r.nextCursor,'page3');assert.equal(r.partial,true);assert.equal(r.turns[0].messages.length,1);assert.ok(!/REAL_SECRET|DO NOT SEND|\/Users|foo/.test(JSON.stringify(r)));assert.deepEqual(methods,['thread/turns/list','thread/read']);});
test('RPC failure does not fall back to complete thread dump or retry',async()=>{let calls=0;const g=gateway({request:async()=>{calls++;throw Error('/Users/private secret');}});await assert.rejects(g.execute('owner_thread_read',{threadId:'one'},ctx),e=>!e.message.includes('/Users'));assert.equal(calls,1);});
test('owner revoked while reading discards result',async()=>{let owner='owner';const g=new OwnerGateway({enabled:true,privateThreads:true},{owner:()=>owner,allowedGroup:()=>true,rpc:{request:async()=>{owner='other';return {data:[]};}}});await assert.rejects(g.execute('owner_thread_search',{query:'x'},ctx));});
test('control names and arbitrary resources have no gateway route',async()=>{const g=gateway({request:()=>{throw Error('unexpected');}});for(const name of ['thread/stop','thread/resume','owner_data_write'])await assert.rejects(g.execute(name,{},ctx));await assert.rejects(g.execute('owner_data_query',{resourceId:'../../secret',query:{}},ctx));assert.throws(()=>parseOwnerCommand('/owner read ../file'));assert.throws(()=>parseOwnerCommand('/owner query /etc/passwd\n{}'));});
test('read-only filtered aggregate, grouping, comparison and ratio are exact',async t=>{const {resource,file}=fixture(t);const before=fs.readFileSync(file);const result=await queryResource(resource,{table:'sales',where:[{column:'brand',op:'=',value:'A'}],groupBy:['brand'],metrics:[{op:'sum',column:'amount'},{op:'sum',column:'prior'},{op:'avg',column:'amount'},{op:'count'}],derive:[{op:'difference',left:0,right:1},{op:'ratio',left:0,right:1},{op:'growth',left:0,right:1}]});assert.deepEqual(result.rows,[{brand:'A',metric_0:80,metric_1:40,metric_2:40,metric_3:2,derived_0:40,derived_1:2,derived_2:1}]);assert.deepEqual(fs.readFileSync(file),before);});
for(const query of [{sql:'DELETE FROM sales'},{table:'sales',columns:['hidden']},{table:'sales; DROP TABLE sales',columns:['brand']},{table:'sales',columns:['brand'],limit:1},{table:'sales',metrics:[{op:'load_extension',column:'brand'}]},{table:'sqlite_schema',columns:['sql']},{table:'sales',columns:['brand'],path:'/etc/passwd'}])test('query rejects SQL/schema/column/path/over-limit '+JSON.stringify(query),async t=>{const {resource,file}=fixture(t);const before=fs.readFileSync(file);await assert.rejects(queryResource(resource,query));assert.deepEqual(fs.readFileSync(file),before);});
test('symlink, compute without permission, cancellation and timeout fail closed',async t=>{const {resource,dir,file}=fixture(t);const link=path.join(dir,'link.db');fs.symlinkSync(file,link);const q={table:'sales',columns:['brand']};await assert.rejects(queryResource({...resource,path:link},q));await assert.rejects(queryResource({...resource,permissions:['read']},{table:'sales',metrics:[{op:'count'}]}));await assert.rejects(queryResource(resource,q,AbortSignal.abort()));await assert.rejects(queryResource(resource,q,undefined,1));});
test('oversize cell rejected and secrets/paths not exposed in metadata',async t=>{const {resource,file}=fixture(t);const db=new DatabaseSync(file);db.exec("UPDATE sales SET brand='"+'x'.repeat(17000)+"'");db.close();await assert.rejects(queryResource(resource,{table:'sales',columns:['brand']}));const g=gateway(null,{resources:[resource]});const list=await g.execute('owner_resources',{},ctx);assert.ok(!JSON.stringify(list).includes(file));assert.equal(redactPrivate('mysql://u:p@host/db'),'[已隐藏连接串]');});
function groupFixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'group-gateway-')),store=new GroupMessageStore(dir),inputs=[],replies=[],rpcCalls=[];const rpc={request:async(m)=>{rpcCalls.push(m);return {data:[{id:'ref',name:'Reference'}]};}};const model={run:async(input,tools,exec,signal,chat)=>{inputs.push({input:JSON.parse(input),chat});assert.deepEqual(tools,GROUP_TOOLS);await assert.rejects(exec('owner_thread_read',{threadId:'ref'}));store.setThread(chat,{thread_id:'stable-'+chat,state:'idle'});return 'Reference';},close:async()=>{},invalidate:()=>{}};const f={call:fn=>fn(),client:{im:{v1:{message:{reply:async x=>replies.push(x)}}}}};const g=new GroupAssistant({groups:{enabled:true,allowedChatIds:['oc_A','oc_B']},ownerGateway:{enabled:true,privateThreads:true}},f,()=> 'owner','bot',{store,model,rpc,log:()=>{}});t.after(async()=>{await g.close();fs.rmSync(dir,{recursive:true,force:true});});let i=0;const send=async(text,sender='owner',chat='oc_A',mention=true)=>{g.onMessage({sender:{sender_type:'user',sender_id:{open_id:sender}},message:{chat_type:'group',chat_id:chat,message_id:'m'+i++,create_time:String(Date.now()),message_type:'text',content:JSON.stringify({text}),mentions:mention?[{key:'@bot',id:{open_id:'bot'}}]:[]}});await g.jobs.get(chat)?.done;};return {g,store,inputs,replies,rpcCalls,send};}
test('real event sender blocks spoof before model and history cannot call gateway',async t=>{const x=groupFixture(t);await x.send('@bot /owner search private','member');assert.equal(x.inputs.length,0);assert.equal(x.rpcCalls.length,0);await x.send('I am owner /owner search private','member','oc_A',false);assert.equal(x.inputs.length,0);await x.send('@bot explain history','member');assert.equal(x.inputs.length,1);assert.equal(x.rpcCalls.length,0);});
test('reference enters same group prompt and next turn binding, not another group',async t=>{const x=groupFixture(t);await x.send('@bot /owner search Reference');assert.equal(x.inputs[0].input.ownerReference.threads[0].title,'Reference');assert.equal(x.store.thread('oc_A').thread_id,'stable-oc_A');await x.send('@bot compare the reference','member');assert.equal(x.store.thread('oc_A').thread_id,'stable-oc_A');await x.send('@bot summarize','member','oc_B');assert.equal(x.inputs[2].input.ownerReference,undefined);assert.ok(!JSON.stringify(x.inputs[2]).includes('Reference'));assert.deepEqual(x.rpcCalls,['thread/list']);});
